import {
  DemoProfileImage1,
  DemoProfileImage2,
  DemoProfileImage3,
  DemoProfileImage4,
  DemoProfileImage5,
  DemoProfileImage6,
  splashOne,
  splashTwo,
} from '../Assets';

export const onBoardinData = [
  {
    id: 0,
    heading: 'Welcome to Salt \n Where Art Meets Hair',
    description: 'Experience the Art of Braiding,\n Anytime, Anywhere.',
  },
  {
    id: 1,
    heading: 'Style that fit \n your daily life style',
    description:
      'Dive into a world of intricate braids and \n stunning hair designs.',
  },
];

export const ChatData = [
  {
    id: 0,
    name: 'Gregory Hayes',
    description: 'Gregory added you to the  ',
    groupName: 'Business Trip',
    image: DemoProfileImage1,
    time: '4:32 PM',
  },
  {
    id: 1,
    name: 'Louis Frank',
    description: 'Benjamin Luis sent a message to',
    groupName: 'trip Home',
    image: DemoProfileImage2,
    time: '4:32 PM',
  },
  {
    id: 2,
    name: 'Liam Andrew',
    description: 'Gregory added you to the',
    groupName: 'Office Meets',
    image: DemoProfileImage3,
    time: '4:32 PM',
  },
  {
    id: 3,
    name: 'Benjamin Luis',
    description: 'William James sent an alert to',
    groupName: 'Office Meets',
    image: DemoProfileImage4,
    time: '4:32 PM',
  },
  {
    id: 4,
    name: 'Louis Frank',
    description: 'Lissa Desouza added you to the',
    groupName: 'Home',
    image: DemoProfileImage5,
    time: '4:32 PM',
  },
  {
    id: 5,
    name: 'Liam Andrew',
    description: 'Gregory added you to the',
    groupName: 'Gentle Mans.',
    image: DemoProfileImage6,
    time: '4:32 PM',
  },
  {
    id: 6,
    name: 'Benjamin Luis',
    description: 'Gregory added you to the',
    groupName: 'Business Trip',
    image: DemoProfileImage1,
    time: '4:32 PM',
  },
  {
    id: 7,
    name: 'Louis Frank',
    description: 'Benjamin Luis sent a message to',
    groupName: 'trip Home',
    image: DemoProfileImage2,
    time: '4:32 PM',
  },
  {
    id: 8,
    name: 'Liam Andrew',
    description: 'Gregory added you to the',
    groupName: 'Office Meets',
    image: DemoProfileImage3,
    time: '4:32 PM',
  },
  {
    id: 9,
    name: 'Louis Frank',
    description: 'William James sent an alert to',
    groupName: 'Office Meets',
    image: DemoProfileImage4,
    time: '4:32 PM',
  },
  {
    id: 10,
    name: 'Liam Andrew',
    description: 'Lissa Desouza added you to',
    groupName: 'Home',
    image: DemoProfileImage5,
    time: '4:32 PM',
  },
  {
    id: 11,
    name: 'Benjamin Luis',
    description: 'Gregory added you to the',
    groupName: 'Gentle Mans.',
    image: DemoProfileImage6,
    time: '4:32 PM',
  },
];

export const Invitation = [
  {
    id: 0,
    name: 'Gregory Hayes',
    description: 'Gregory added you to the  ',
    groupName: 'Business Trip',
    image: DemoProfileImage1,
    time: '4:32 PM',
    initialStatus: 'pending',
  },
  {
    id: 1,
    name: 'Louis Frank',
    description: 'Benjamin Luis sent a message to',
    groupName: 'trip Home',
    image: DemoProfileImage2,
    time: '4:32 PM',
    initialStatus: 'rejected',
  },
  {
    id: 2,
    name: 'Liam Andrew',
    description: 'Gregory added you to the',
    groupName: 'Office Meets',
    image: DemoProfileImage3,
    time: '4:32 PM',
    initialStatus: 'rejected',
  },
  {
    id: 3,
    name: 'Benjamin Luis',
    description: 'William James sent an alert to',
    groupName: 'Office Meets',
    image: DemoProfileImage4,
    time: '4:32 PM',
    initialStatus: 'accepted',
  },
  {
    id: 4,
    name: 'Louis Frank',
    description: 'Lissa Desouza added you to the',
    groupName: 'Home',
    image: DemoProfileImage5,
    time: '4:32 PM',
    initialStatus: 'rejected',
  },
  {
    id: 5,
    name: 'Liam Andrew',
    description: 'Gregory added you to the',
    groupName: 'Gentle Mans.',
    image: DemoProfileImage6,
    time: '4:32 PM',
    initialStatus: 'accepted',
  },
  {
    id: 6,
    name: 'Benjamin Luis',
    description: 'Gregory added you to the',
    groupName: 'Business Trip',
    image: DemoProfileImage1,
    time: '4:32 PM',
    initialStatus: 'accepted',
  },
  {
    id: 7,
    name: 'Louis Frank',
    description: 'Benjamin Luis sent a message to',
    groupName: 'trip Home',
    image: DemoProfileImage2,
    time: '4:32 PM',
    initialStatus: 'rejected',
  },
  {
    id: 8,
    name: 'Liam Andrew',
    description: 'Gregory added you to the',
    groupName: 'Office Meets',
    image: DemoProfileImage3,
    time: '4:32 PM',
    initialStatus: 'accepted',
  },
  {
    id: 9,
    name: 'Louis Frank',
    description: 'William James sent an alert to',
    groupName: 'Office Meets',
    image: DemoProfileImage4,
    time: '4:32 PM',
    initialStatus: 'rejected',
  },
  {
    id: 10,
    name: 'Liam Andrew',
    description: 'Lissa Desouza added you to',
    groupName: 'Home',
    image: DemoProfileImage5,
    time: '4:32 PM',
    initialStatus: 'accepted',
  },
  {
    id: 11,
    name: 'Benjamin Luis',
    description: 'Gregory added you to the',
    groupName: 'Gentle Mans.',
    image: DemoProfileImage6,
    time: '4:32 PM',
    initialStatus: 'accepted',
  },
];

export const frequentTrips = [
  {
    id: 0,
    name: 'Office',
    image: DemoProfileImage3,
  },
  {
    id: 1,
    name: 'Home',
    image: DemoProfileImage5,
  },
  {
    id: 2,
    name: 'Business',
    image: DemoProfileImage1,
  },
  {
    id: 3,
    name: 'Visit',
    image: DemoProfileImage5,
  },
  {
    id: 0,
    name: 'Office',
    image: DemoProfileImage3,
  },
  {
    id: 1,
    name: 'Home',
    image: DemoProfileImage5,
  },
  {
    id: 2,
    name: 'Business',
    image: DemoProfileImage1,
  },
  {
    id: 3,
    name: 'Visit',
    image: DemoProfileImage5,
  },
  {
    id: 0,
    name: 'Office',
    image: DemoProfileImage3,
  },
  {
    id: 1,
    name: 'Home',
    image: DemoProfileImage5,
  },
  {
    id: 2,
    name: 'Business',
    image: DemoProfileImage1,
  },
  {
    id: 3,
    name: 'Visit',
    image: DemoProfileImage5,
  },
];

export const msgs = [
  {
    user: 'sender',
    name: 'William James',
    msg: 'Lorem Ipsum is simply dummy text of the printing.',
    time: '3:15 PM',
    userEmail: 'abc@gmail.com',
  },
  {
    user: 'reciever',
    name: 'William James',
    msg: 'Lorem Ipsum is simply dumm',
    time: '3:15 PM',
  },
  {
    user: 'sender',
    name: 'William James',
    msg: 'Lorem Ipsum is simply dummy text of the printing. Lorem Ipsum is simply dummy text of the printing.',
    time: '3:15 PM',
    userEmail: 'abc@gmail.com',
  },
  {
    user: 'reciever',
    name: 'William James',
    msg: 'Lorem Ipsum is simply dummy text of the printing. Lorem Ipsum is simply dummy text of the printing. Lorem Ipsum is simply dummy text of the printing lines in.',
    time: '3:15 PM',
  },
  {
    user: 'sender',
    name: 'William James',
    msg: 'Lorem Ipsum is simply dummy text of the printing.',
    time: '3:15 PM',
    userEmail: 'abc@gmail.com',
  },
  {
    user: 'reciever',
    name: 'William James',
    msg: 'Lorem Ipsum is simply dumm',
    time: '3:15 PM',
  },
  {
    user: 'reciever',
    name: 'William James',
    msg: 'Lorem Ipsum is simply dummy text of the printing. Lorem Ipsum is simply dummy text of the printing. Lorem Ipsum is simply dummy text of the printing lines in.',
    time: '3:15 PM',
  },
  {
    user: 'sender',
    name: 'William James',
    msg: 'Lorem Ipsum is simply dummy text of the printing.',
    time: '3:15 PM',
    userEmail: 'abc@gmail.com',
  },
  {
    user: 'reciever',
    name: 'William James',
    msg: 'Lorem Ipsum is simply dumm',
    time: '3:15 PM',
  },
];

export const trips = [
  {
    tripProfile: DemoProfileImage1,
    tripName: 'Business trip',
    member: '15 members',
    status: 'Active',
  },
  {
    tripProfile: DemoProfileImage2,
    tripName: 'Outings',
    member: '10 members',
    status: 'Inactive',
  },
  {
    tripProfile: DemoProfileImage3,
    tripName: 'Home',
    member: '5 members',
    status: 'Active',
  },
  {
    tripProfile: DemoProfileImage1,
    tripName: 'Business trip',
    member: '15 members',
    status: 'Active',
  },
  {
    tripProfile: DemoProfileImage2,
    tripName: 'Outings',
    member: '10 members',
    status: 'Inactive',
  },
  {
    tripProfile: DemoProfileImage3,
    tripName: 'Home',
    member: '5 members',
    status: 'Active',
  },
];

export const tripsTypes = [
  {
    id: 'myTrip',
    des: 'Track where your loved ones are - keep them safe!',
    title: 'Keep A Track',
    details:
      'Stay in the loop during your events or trips with our Real-Time Location Sharing feature. As the host, you can effortlessly keep track of all participants who have accepted the invitation.',
  },
  {
    id: 'groupTrip',
    des: 'Track each other across every mile by location sharing',
    title: 'Mutual Tracking',
    details:
      "Whether it's a meetup, adventure, or any group activity, stay connected and aware of each other's movements. Enjoy a seamless and secure tracking experience that fosters teamwork and ensures safety throughout your shared journey.",
  },
  {
    id: 'personalTrip',
    des: 'Stay safe, stay connected! Share your real-time location with just a tap.',
    title: 'Share Location',
    details:
      'Easily connect with your loved ones. As the host, you can share your real-time location with friends and family, allowing them to track you throughout your journey.',
  },
];

export const tripProfileColors = [
  '#FFD700',
  '#DAA520',
  '#FF7F50',
  '#9ACD32',
  '#90EE90',
  '#66CDAA',
  '#00FFFF',
  '#48D1CC',
  '#6495ED',
  '#4169E1',
  '#00BFFF',
];
